### ISSUE TITLE
Theatre display problem 

### ISSUE THREAD

**Issue by Divyesh-20** [agadesh/BookMyShow-Clone#1]
When we try to open theatre most of time it shows no show available why is it so

**Comment by agadesh** [comment]
Hey @Divyesh-20,  shows data is just stored in a JSON with calculated values of +1 and +2 of today's date. Maybe there is some issue, I will check. Thanks for the info.

**Comment by Divyesh-20** [comment]
I would like to elaborate the problem when we try to open the project
through any browser sometimes it shows theatre and sometimes nothing is
visible
I have used your project to make our project with some modifications if you
would want to have a look I would be happy to share with you

**Comment by agadesh** [comment]
Issue is resolved please check [This commit](https://github.com/agadesh/BookMyShow-Clone/commit/655d87caf52986ea950998881da42340b775a570)

**Comment by Divyesh-20** [comment]
Yes, it is working.
i want to discuss with you i have used yours code and made few
modifications like adding php mysql etc many times it works but most of
times it doesn't if you could please help use to resolve those issues it
would be great help we have use yours project for our project in cs
enginnering 2nd year but they asked us for database so for it we joined
some databases like login,signin,logincount but many issues are happening
would like to help us

**Comment by Divyesh-20** [comment]
Ok leave everything else I just want to know can you just please create a
admin module just an HTML page will be sufficient only one thing we want is
to add and remove movies and theatres dynamically from outside please can
you help it's very urgent
Atleast tell us how can we do that please


DIVYESH SHINDE
